# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APP_ID = "com.duc.MDCiCd"

default_platform(:ios)

platform :ios do
    before_all do
        sh(command: "rm -vfr ~/Library/Developer/Xcode/Archives/*")
        clear_derived_data()
        xcode_select("/Applications/Xcode.app")
    end


    lane :release do
        match(type: "appstore", app_identifier: APP_ID)
        increment_build_number(xcodeproj: "MDCiCd.xcodeproj")
        build_app(
    	   scheme: "MDCiCd",
    	   export_method: "app-store"
        )
        upload_to_testflight
    end


    # Deletes files created as result of running gym, cert, sigh or download_dsyms
    after_all do |lane|
        clean_build_artifacts
    end
end