# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APP_ID = "com.duc.MDCiCd"

default_platform(:ios)

platform :ios do
#  desc "Push a new beta build to TestFlight"
  lane :development do
    
#match(type: "development", app_identifier: APP_ID)
increment_build_number(xcodeproj: "MDCiCd.xcodeproj")
    build_app(
	scheme: "MDCiCd")
    upload_to_testflight
  end
end