name: GitHub Actions Demo
on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Build"
      - run: echo "Test"
      - run: echo "Done"
      - name: Build and test
        run: fastlane development
